services:
  backend:
    image: juuunoz/quirknotes_backend:latest
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - ENV=Docker

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  frontend:
    image: juuunoz/quirknotes_frontend:latest
    ports:
      - "3000:80"