# Use the official Node.js image as the base image for frontend
FROM node:20.0.0-alpine AS frontend

# Set working directory
WORKDIR /app/quirknotes/backend

# Copy backend package files
COPY quirknotes/backend/package*.json ./

# Install dependencies as needed
RUN npm install express mongodb bcrypt jsonwebtoken

RUN npm install --save-dev nodemon

# Copy in source code
COPY quirknotes/backend ./

# Run backend
RUN npm run start &
