# Use the latest mongodb image to setup backend
FROM mongo:latest AS backend

# Setup Node.js and npm
FROM node:20.0.0-alpine AS node-backend

#install node.js and npm
RUN apt-get update && apt-get install -y \
    nodejs \
    npm

# Set working directory
WORKDIR /app/quirknotes/backend

# Copy backend package files
COPY quirknotes/backend/package*.json ./

# Install dependencies as needed
RUN npm install express mongodb bcrypt jsonwebtoken

RUN npm install --save-dev nodemon

# Copy in source code
COPY quirknotes/backend ./

# Expose port 4000
EXPOSE 4000

# Command to run the backend server
CMD ["npm", "start"]