# Use MongoDB image as base image for backend
FROM mongo:latest

# Set working directory
WORKDIR /app/quirknotes/backend

# Copy backend package files
COPY quirknotes/backend/package*.json ./

# Install dependencies as needed
RUN npm install express mongodb bcrypt jsonwebtoken
RUN npm install --save-dev nodemon

# Copy in source code
COPY quirknotes/backend ./

# Run backend
RUN npm run dev
